apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitea
spec:
  selector:
    app: {{ .Release.Name }}-gitea
    chart: {{ .Chart.Version }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.gitea.port }}
      targetPort: {{ .Values.gitea.port }}
