apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Version }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
  type: NodePort
