apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  default.conf: |
    server {
      listen {{ .Values.nginx.port }};
      location / {
        proxy_pass http://{{ .Release.Name }}-gitea:{{ .Values.gitea.port }};
      }
    }


