apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
    chart: {{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
      chart: {{ .Chart.Version }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
        chart: {{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: nginx:{{ .Values.nginx.imageTag }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-nginx-config
